name: ansi_escapes
description: ANSI escape codes for manipulating the terminal
version: 1.0.4
homepage: https://github.com/shan-shaji/ansi-escapes-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependencies: 
